videos:
  greece:
    path: ./videos/greece.mp4
    focal_length: 270
  road:
    path: ./videos/road.mp4
    focal_length: 270
  road_reverse:
    path: ./videos/road_reverse.mp4
    focal_length: 340
  drone:
    path: ./videos/drone.mp4
    focal_length: 660
  drone_reverse:
    path: ./videos/drone_reverse.mp4
    focal_length: 520
  swiz:
    path: ./videos/swiz.mp4
    focal_length: 270
